[connections.supabase]
host = "db.xddtqbtavspzuqfpuiid.supabase.co"
database = "postgres"
user = "postgres"
password = "erfgvb13"
port = "5432"

[openai]
api_key = "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"
